esphome:
  name: distance_sensor_node
  platform: ESP32
  board: esp32dev

wifi:
  ssid: {ssid}
  password: {password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: {ssid}
    password: {password}

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: ultrasonic
    trigger_pin: GPIO27
    echo_pin: GPIO26
    name: "Distance Sensor (Ultrasonic)"
    id: distance_sensor
    retain: False
    discovery: True
    availability:
      topic: distance_sensor/status
      payload_available: 1
      payload_not_available: 0
    state_topic: distance_sensor/distance
    unit_of_measurement: ""

mqtt:
  broker: {broker_ip}
  id: mqtt_client
  on_message:
    - topic: distance_sensor/query
      qos: 0
      then:
        - mqtt.publish_json:
            topic: distance_sensor/query_result
            payload: |-
              root["distance"] = id(distance_sensor).state;
            qos: 0
            retain: false